package gs.ad.utils.ads.error;

public enum AdmErrorType {
    LIST_AD_ID_IS_EMPTY,
    AD_ID_IS_NOT_EXIST,
    NETWORK_IS_NOT_AVAILABLE,
    AD_IS_EXISTED,
    ACTIVITY_IS_NOT_AVAILABLE,
    ACTIVITY_IS_FINISHING,
    ACTIVITY_IS_DESTROYED,
    CLIENT_HAVE_SUB,
    CLIENT_HAVE_BEEN_REMOVED_AD,
    OTHER
}
